# -*- coding: utf-8 -*-
"""WVS Visualization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iBePDm5949UFAccdRMsK6rQIBHF0jMQC
"""

from google.colab import drive
drive.mount('/content/drive')

folder_path = '/content/drive/MyDrive/MSCS/DataViz'
print(f"You can now access your folder at: {folder_path}")

import os
if os.path.exists(folder_path):
    print(f"Contents of {folder_path}:")
    for item in os.listdir(folder_path):
        print(item)
else:
    print(f"The folder {folder_path} does not exist or is not accessible.")

import pandas as pd

file_path = '/content/drive/MyDrive/MSCS/DataViz/WVS_Wave_7_United_States_Csv_v5.1.csv'
df = pd.read_csv(file_path, sep=';', index_col=False)

print(f"New column count: {len(df.columns)}")
print(df.head())

import numpy as np
df.replace([-1, -2, -3, -4, -5], np.nan, inplace=True)
print("Replaced values in-place.")
print(df.head())

missing_data_raw = df.isnull().sum()
missing_data_raw = missing_data_raw[missing_data_raw > 0]
missing_percentage = (missing_data_raw / len(df)) * 100

missing_info = pd.DataFrame({
    'Missing Count': missing_data_raw,
    'Missing Percentage': missing_percentage
}).sort_values(by='Missing Percentage', ascending=False)

print("Missing values summary:")
print(missing_info.head(20))

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12, 8))
sns.barplot(x=missing_info.head(20).index, y=missing_info.head(20)['Missing Percentage'], hue=missing_info.head(20).index, palette='viridis', legend=False)
plt.xlabel('Columns')
plt.ylabel('Missing Percentage (%)')
plt.title('Top 20 Columns with Missing Values')
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

import numpy as np

numerical_cols = df.select_dtypes(include=np.number).columns

capped_counts = {}

for col in numerical_cols:
    if df[col].nunique() <= 1:
        print(f"Column '{col}': Skipped capping due to insufficient variance")
        capped_counts[col] = 0
        continue

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers_lower = df[col][df[col] < lower_bound].count()
    outliers_upper = df[col][df[col] > upper_bound].count()

    df[col] = np.where(df[col] < lower_bound, lower_bound, df[col])
    df[col] = np.where(df[col] > upper_bound, upper_bound, df[col])

    capped_counts[col] = outliers_lower + outliers_upper

print("\nSummary of capped values")
for col, count in capped_counts.items():
    if count > 0:
        print(f"  Column '{col}': {count} values capped")

print("\nOutlier capping process completed.")
display(df.head())

import numpy as np
import pandas as pd

print("--- Re-evaluating Outliers ---")
print("Using Z-score method")
print("Using IQR method")

df_no_outliers = df.copy()

numerical_cols = df_no_outliers.select_dtypes(include=np.number).columns

for col in numerical_cols:
    if df_no_outliers[col].isnull().all():
        print(f"Column '{col}': Contains only NaN values, skipping outlier check.")
        continue

    z_scores = np.abs((df_no_outliers[col] - df_no_outliers[col].mean()) / df_no_outliers[col].std())
    outlier_threshold_zscore = 3
    z_score_outliers_count = df_no_outliers[z_scores > outlier_threshold_zscore].shape[0]

    Q1 = df_no_outliers[col].quantile(0.25)
    Q3 = df_no_outliers[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    iqr_outliers_count = df_no_outliers[(df[col] < lower_bound) | (df_no_outliers[col] > upper_bound)].shape[0]

    print(f"Column '{col}':")
    print(f"  Z-score outliers: {z_score_outliers_count} ({(z_score_outliers_count / len(df_no_outliers)) * 100:.2f}%)")
    print(f"  IQR outliers: {iqr_outliers_count} ({(iqr_outliers_count / len(df_no_outliers)) * 100:.2f}%)\n")

print("Outlier re-evaluation completed.")

missing_data = df_no_outliers.isnull().sum()
missing_data = missing_data[missing_data > 0]
missing_percentage = (missing_data / len(df)) * 100

missing_info = pd.DataFrame({
    'Missing Count': missing_data,
    'Missing Percentage': missing_percentage
}).sort_values(by='Missing Percentage', ascending=False)

print("Missing values summary:")
print(missing_info.head(20))

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12, 8))
sns.barplot(x=missing_info.head(20).index, y=missing_info.head(20)['Missing Percentage'], hue=missing_info.head(20).index, palette='viridis', legend=False)
plt.xlabel('Columns')
plt.ylabel('Missing Percentage (%)')
plt.title('Top 20 Columns with Missing Values')
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()





from sklearn.impute import KNNImputer
import numpy as np

df_imputed_knn = df_no_outliers.copy()

numerical_cols = df_imputed_knn.select_dtypes(include=np.number).columns

knn_imputer = KNNImputer(n_neighbors=5, weights='uniform')

df_imputed_knn[numerical_cols] = knn_imputer.fit_transform(df_imputed_knn[numerical_cols])
print("KNN Imputation completed.")

print("\nMissing values after KNN imputation (top 20):")
missing_after_knn = df_imputed_knn[numerical_cols].isnull().sum()
missing_after_knn = missing_after_knn[missing_after_knn > 0].sort_values(ascending=False)
if not missing_after_knn.empty:
    print(missing_after_knn.head(20))
else:
    print("No missing values in numerical columns after KNN imputation.")

print("\nDataFrame head after KNN imputation:")
display(df_imputed_knn.head())

missing_data = df_imputed_knn.isnull().sum()
missing_data = missing_data[missing_data > 0]
missing_percentage = (missing_data / len(df_imputed_knn)) * 100

missing_info = pd.DataFrame({
    'Missing Count': missing_data,
    'Missing Percentage': missing_percentage
}).sort_values(by='Missing Percentage', ascending=False)

print("Missing values summary:")
print(missing_info.head(20))

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12, 8))
sns.barplot(x=missing_info.head(20).index, y=missing_info.head(20)['Missing Percentage'], hue=missing_info.head(20).index, palette='viridis', legend=False)
plt.xlabel('Columns')
plt.ylabel('Missing Percentage (%)')
plt.title('Top 20 Columns with Missing Values')
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

pip install "altair[all]"

source = df_imputed_knn.copy()

print(source['Q254'].unique())
print(source['Q130'].unique())

"""### Log Transformation for Skewed Columns

Log transformation is a mathematical operation that converts a variable by applying the logarithm function. It is commonly used to address **right-skewed (positively skewed)** distributions, where a large number of data points are concentrated on the left side (lower values) and a few extreme values exist on the right side (higher values).

**Why use Log Transformation?**
1.  **Reduce Skewness**: It compresses the larger values and stretches out the smaller values, making the distribution more symmetrical and closer to a normal distribution.
2.  **Stabilize Variance**: It can help in cases where the variability of data increases with the mean, leading to more stable variance across the data range.
3.  **Linearize Relationships**: In regression analysis, log transformations can linearize relationships between variables that are otherwise curvilinear.

**How to Apply:**
*   **`numpy.log()`**: Use this for data that contains only positive values (`> 0`).
*   **`numpy.log1p()`**: This function calculates `log(1+x)`. It's particularly useful when your data contains zero values, as `log(0)` is undefined. By adding 1 before taking the logarithm, you avoid errors and still transform the data effectively.

**Example:** Let's assume you have a column like `Q28` or `J_INTDATE` which had a high number of outliers and might be skewed. We will apply `np.log1p()` to ensure handling of any zero values that might implicitly be there (or result from capping). First, we'll check the skewness before and after the transformation.
"""

import numpy as np

numerical_cols = df_imputed_knn.select_dtypes(include=np.number).columns

capped_counts = {}

for col in numerical_cols:
    if df_imputed_knn[col].nunique() <= 1:
        print(f"Column '{col}': Skipped capping due to insufficient variance.")
        capped_counts[col] = 0
        continue

    Q1 = df_imputed_knn[col].quantile(0.25)
    Q3 = df_imputed_knn[col].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers_lower = df_imputed_knn[col][df_imputed_knn[col] < lower_bound].count()
    outliers_upper = df_imputed_knn[col][df_imputed_knn[col] > upper_bound].count()

    df_imputed_knn[col] = np.where(df_imputed_knn[col] < lower_bound, lower_bound, df_imputed_knn[col])
    df_imputed_knn[col] = np.where(df_imputed_knn[col] > upper_bound, upper_bound, df_imputed_knn[col])

    capped_counts[col] = outliers_lower + outliers_upper

print("\nSummary of capped values per numerical column:")
for col, count in capped_counts.items():
    if count > 0:
        print(f"  Column '{col}': {count} values capped")

print("\nOutlier capping process completed. Displaying head of the updated DataFrame:")
display(df_imputed_knn.head())

import altair as alt
import pandas as pd

pride_map = {
    1: 'Very proud',
    2: 'Quite proud',
    3: 'Not very proud',
    4: 'Not at all proud',
    5: 'I am not [nationality]'
}

migration_map = {
    1: 'Allow many to come',
    2: 'Allow some to come',
    3: 'Allow few to come',
    4: 'Allow none to come'
}

migration_order = ['Allow many to come', 'Allow some to come', 'Allow few to come', 'Allow none to come']

full_pride_order = ["Very proud", "Quite proud", "Not very proud", "Not at all proud", "I am not [nationality]"]

source['Pride_label'] = source['Q254'].round().map(pride_map)
source['Migration_label'] = source['Q130'].round().map(migration_map)

base = alt.Chart(source).transform_filter(
    "datum.Pride_label != null && datum.Migration_label != null"
).encode(
    x=alt.X('Pride_label:O', sort=full_pride_order, title='National Pride'),
    y=alt.Y('Migration_label:O', sort=migration_order, title='Migration Policy Attitude')
)

heatmap = base.mark_rect().encode(
    color=alt.Color('count():Q',
                    title='Respondents',
                    scale=alt.Scale(scheme='viridis'))
)

text = base.mark_text(baseline='middle').encode(
    text='count():Q',
    color=alt.condition(alt.datum['count_*'] > (source.shape[0]/20),
                        alt.value('white'),
                        alt.value('black'))
)

final_chart = (heatmap + text).properties(
    title="Impact of National Pride on Migration Attitudes (KNN Imputed)",
    width=400,
    height=400
)

final_chart.display()

import pandas as pd
import altair as alt

alt.data_transformers.enable("vegafusion")

pride_map = {
    1: 'Very proud',
    2: 'Quite proud',
    3: 'Not very proud',
    4: 'Not at all proud',
    5: 'I am not [nationality]'
}

migration_map = {
    1: 'Allow many to come',
    2: 'Allow some to come',
    3: 'Allow few to come',
    4: 'Allow none to come'
}

pride_order = ["Very proud", "Quite proud", "Not very proud", "Not at all proud", "I am not [nationality]", "Missing"]
migration_order = ["Allow many to come", "Allow some to come", "Allow few to come", "Allow none to come", "Missing"]

source_raw = df.copy()
source_knn = df_imputed_knn.copy()


source_raw['Pride_label'] = source_raw['Q254'].map(pride_map).fillna('Missing')
source_raw['Migration_label'] = source_raw['Q130'].map(migration_map).fillna('Missing')

source_knn['Pride_label'] = source_knn['Q254'].map(lambda x: pride_map.get(int(x)) if pd.notna(x) else 'Missing')
source_knn['Migration_label'] = source_knn['Q130'].map(lambda x: migration_map.get(int(x)) if pd.notna(x) else 'Missing')

source_raw['Dataset'] = 'Original'
source_knn['Dataset'] = 'KNN Imputed'

combined_source = pd.concat([source_raw, source_knn], ignore_index=True)

aggregated_data = combined_source.groupby(
    ['Dataset', 'Pride_label', 'Migration_label']
).size().reset_index(name='count')

base = alt.Chart(aggregated_data).encode(
    x=alt.X('Pride_label:O', sort=pride_order, title='National Pride'),
    y=alt.Y('Migration_label:O', sort=migration_order, title='Migration Attitude')
)

heatmap = base.mark_rect().encode(
    color=alt.condition(
        "(datum.Pride_label === 'Missing') || (datum.Migration_label === 'Missing')",
        alt.value('lightgrey'),
        alt.Color('count:Q', scale=alt.Scale(scheme='viridis'))
    ),
    tooltip=['Dataset:N', 'Pride_label:N', 'Migration_label:N', 'count:Q']
)

text = base.mark_text(baseline='middle').encode(
    text='count:Q',
    color=alt.condition(
        alt.datum['count'] > aggregated_data['count'].max() / 2,
        alt.value('black'),
        alt.value('white')
    )
)

comparison_chart = (heatmap + text).properties(
    width=300,
    height=300
).facet(
    column='Dataset:N'
).properties(
    title="Comparison: Original vs. KNN Imputed Data"
).resolve_scale(
    color='shared'
)

comparison_chart

print("Missing in Q254:", df['Q254'].isna().sum())
print("Missing in Q130:", df['Q130'].isna().sum())

missing_migration_rows = combined_source[combined_source['Migration_label'] == 'Missing']
print(f"Number of rows where 'Migration_label' is 'Missing': {len(missing_migration_rows)}")

missing_migration_distribution = missing_migration_rows['Dataset'].value_counts().reset_index()
missing_migration_distribution.columns = ['Dataset', 'Missing_Count']
print("\nDistribution of 'Missing' Migration_label values across datasets:")
display(missing_migration_distribution)

missing_pride_rows = combined_source[combined_source['Pride_label'] == 'Missing']
print(f"Number of rows where 'Pride_label' is 'Missing': {len(missing_pride_rows)}")

missing_pride_distribution = missing_pride_rows['Dataset'].value_counts().reset_index()
missing_pride_distribution.columns = ['Dataset', 'Missing_Count']
print("Distribution of 'Missing' Pride_label values across datasets:")
display(missing_pride_distribution)

missing_pride_rows = combined_source[combined_source['Pride_label'] == 'Missing']
print(f"Number of rows where 'Pride_label' is 'Missing': {len(missing_pride_rows)}")
display(missing_pride_rows.head())

fips_to_name = {
    1: 'Alabama', 2: 'Alaska', 4: 'Arizona', 5: 'Arkansas', 6: 'California',
    8: 'Colorado', 9: 'Connecticut', 10: 'Delaware', 11: 'District of Columbia',
    12: 'Florida', 13: 'Georgia', 15: 'Hawaii', 16: 'Idaho', 17: 'Illinois',
    18: 'Indiana', 19: 'Iowa', 20: 'Kansas', 21: 'Kentucky', 22: 'Louisiana',
    23: 'Maine', 24: 'Maryland', 25: 'Massachusetts', 26: 'Michigan',
    27: 'Minnesota', 28: 'Mississippi', 29: 'Missouri', 30: 'Montana',
    31: 'Nebraska', 32: 'Nevada', 33: 'New Hampshire', 34: 'New Jersey',
    35: 'New Mexico', 36: 'New York', 37: 'North Carolina', 38: 'North Dakota',
    39: 'Ohio', 40: 'Oklahoma', 41: 'Oregon', 42: 'Pennsylvania',
    44: 'Rhode Island', 45: 'South Carolina', 46: 'South Dakota', 47: 'Tennessee',
    48: 'Texas', 49: 'Utah', 50: 'Vermont', 51: 'Virginia', 53: 'Washington',
    54: 'West Virginia', 55: 'Wisconsin', 56: 'Wyoming', 60: 'American Samoa',
    66: 'Guam', 69: 'Northern Mariana Islands', 72: 'Puerto Rico', 78: 'Virgin Islands'
}

wvs_fips_correction_map = {}
print("FIPS to state name mapping and WVS FIPS correction map was started.")

wvs_fips_correction_map[50] = 56
print("Updated wvs_fips_correction_map:")
print(wvs_fips_correction_map)

state_data = df_imputed_knn.copy()

state_data = state_data[state_data['Q50'] > 0]
state_data = state_data[state_data['Q235'] > 0]

state_data['derived_state_fips'] = state_data['N_REGION_WVS'].apply(
    lambda x: int(str(int(x))[-2:]) if pd.notnull(x) else np.nan
)

state_data['derived_state_fips'] = state_data['derived_state_fips'].map(wvs_fips_correction_map).fillna(state_data['derived_state_fips'])

state_data.dropna(subset=['derived_state_fips'], inplace=True)

state_data['derived_state_fips'] = state_data['derived_state_fips'].astype(int)

state_data['state_name'] = state_data['derived_state_fips'].map(fips_to_name)

state_data.dropna(subset=['state_name'], inplace=True)

df_state_centroids = state_data.groupby('state_name').agg(
    financial_satisfaction=('Q50', 'mean'),
    fin_std=('Q50', 'std'),
    strong_leader_pref=('Q235', 'mean'),
    lead_std=('Q235', 'std'),
    n_size=('Q50', 'count')
).reset_index()

print("\nAggregated state data head (checking for Wyoming):")
display(df_state_centroids.head())

if 'Wyoming' in df_state_centroids['state_name'].values:
    print("Wyoming is now present in df_state_centroids.")
    display(df_state_centroids[df_state_centroids['state_name'] == 'Wyoming'])
else:
    print("Wyoming is still NOT present in df_state_centroids.")

from vega_datasets import data

capitals = data.us_state_capitals()
print("Capitals DataFrame head:")
display(capitals.head())

print("\nChecking if Wyoming is in the capitals DataFrame:")
wyoming_in_capitals = capitals[capitals['state'] == 'Wyoming']
if not wyoming_in_capitals.empty:
    print("Wyoming is present in the capitals dataset.")
    display(wyoming_in_capitals)
else:
    print("Wyoming is NOT present in the capitals dataset.")

import pandas as pd
import numpy as np
import altair as alt

def get_global_stats(df, label):
    z_score = 1.96

    if 'Q50' in df.columns and 'Q235' in df.columns:
        n = len(df)
        fin_mean = df['Q50'].mean()
        fin_std = df['Q50'].std()
        fin_se = fin_std / np.sqrt(n)

        lead_mean = df['Q235'].mean()
        lead_std = df['Q235'].std()
        lead_se = lead_std / np.sqrt(n)
    else:
        raise ValueError("DataFrame does not contain expected 'Q50' or 'Q235' columns for global stats calculation.")

    return pd.DataFrame([
        {
            'Dataset': label,
            'fin_mean': fin_mean,
            'fin_min': fin_mean - (z_score * fin_se),
            'fin_max': fin_mean + (z_score * fin_se),
            'lead_mean': lead_mean,
            'lead_min': lead_mean - (z_score * lead_se),
            'lead_max': lead_mean + (z_score * lead_se),
            'n_size': n
        }
    ])

state_data_raw = df.copy()

state_data_raw = state_data_raw[state_data_raw['Q50'] > 0]
state_data_raw = state_data_raw[state_data_raw['Q235'] > 0]

state_data_raw['derived_state_fips'] = state_data_raw['N_REGION_WVS'].apply(
    lambda x: int(str(int(x))[-2:]) if pd.notnull(x) else np.nan
)

state_data_raw['derived_state_fips'] = state_data_raw['derived_state_fips'].map(wvs_fips_correction_map).fillna(state_data_raw['derived_state_fips'])

state_data_raw.dropna(subset=['derived_state_fips'], inplace=True)

state_data_raw['derived_state_fips'] = state_data_raw['derived_state_fips'].astype(int)

state_data_raw['state_name'] = state_data_raw['derived_state_fips'].map(fips_to_name)

state_data_raw.dropna(subset=['state_name'], inplace=True)

comparison_df = pd.concat([
    get_global_stats(state_data_raw, 'Raw Data'),
    get_global_stats(df_imputed_knn, 'KNN Imputed')
])

base = alt.Chart(comparison_df).encode(
    y=alt.Y('Dataset:N', title=None)
)

lines = base.mark_rule(color='#ccc', strokeWidth=2).encode(
    x=alt.X('fin_mean:Q', title='Score (1-10)'),
    x2='lead_mean:Q'
)

fin_dots = base.mark_circle(size=150, color='#1f77b4').encode(
    x='fin_mean:Q',
    tooltip=['fin_mean', 'n_size']
)
fin_err = base.mark_errorbar(ticks=True, color='#1f77b4').encode(
    x='fin_min:Q',
    x2='fin_max:Q'
)

lead_dots = base.mark_circle(size=150, color='#ff7f0e').encode(
    x='lead_mean:Q',
    tooltip=['lead_mean', 'n_size']
)
lead_err = base.mark_errorbar(ticks=True, color='#ff7f0e').encode(
    x='lead_min:Q',
    x2='lead_max:Q'
)

final_agg_chart = (lines + fin_err + lead_err + fin_dots + lead_dots).properties(
    width=500,
    height=120,
    title="Global Comparison: Financial Satisfaction (Blue) vs Leader Preference (Orange)"
)

final_agg_chart.display()

import altair as alt
import pandas as pd
import numpy as np

state_data_raw = df.copy()

state_data_raw = state_data_raw[state_data_raw['Q50'] > 0]
state_data_raw = state_data_raw[state_data_raw['Q235'] > 0]

state_data_raw['derived_state_fips'] = state_data_raw['N_REGION_WVS'].apply(
    lambda x: int(str(int(x))[-2:]) if pd.notnull(x) else np.nan
)

state_data_raw['derived_state_fips'] = state_data_raw['derived_state_fips'].map(wvs_fips_correction_map).fillna(state_data_raw['derived_state_fips'])

state_data_raw.dropna(subset=['derived_state_fips'], inplace=True)

state_data_raw['derived_state_fips'] = state_data_raw['derived_state_fips'].astype(int)

state_data_raw['state_name'] = state_data_raw['derived_state_fips'].map(fips_to_name)

state_data_raw.dropna(subset=['state_name'], inplace=True)

df_state_centroids_raw = state_data_raw.groupby('state_name').agg(
    financial_satisfaction=('Q50', 'mean'),
    fin_std=('Q50', 'std'),
    strong_leader_pref=('Q235', 'mean'),
    lead_std=('Q235', 'std'),
    n_size=('Q50', 'count')
).reset_index()

viz_data_raw = df_state_centroids_raw.merge(capitals, left_on='state_name', right_on='state', how='inner')

viz_data_raw.dropna(subset=['lon', 'lat'], inplace=True)

viz_data_raw['combined'] = viz_data_raw['financial_satisfaction'] + viz_data_raw['strong_leader_pref']
viz_data_sorted_raw = viz_data_raw.sort_values('combined', ascending=False)

z_score = 1.96
viz_data_sorted_raw['fin_se'] = viz_data_sorted_raw['fin_std'] / np.sqrt(viz_data_sorted_raw['n_size'])
viz_data_sorted_raw['fin_error_min'] = viz_data_sorted_raw['financial_satisfaction'] - (z_score * viz_data_sorted_raw['fin_se'])
viz_data_sorted_raw['fin_error_max'] = viz_data_sorted_raw['financial_satisfaction'] + (z_score * viz_data_sorted_raw['fin_se'])
viz_data_sorted_raw['lead_se'] = viz_data_sorted_raw['lead_std'] / np.sqrt(viz_data_sorted_raw['n_size'])
viz_data_sorted_raw['lead_error_min'] = viz_data_sorted_raw['strong_leader_pref'] - (z_score * viz_data_sorted_raw['lead_se'])
viz_data_sorted_raw['lead_error_max'] = viz_data_sorted_raw['strong_leader_pref'] + (z_score * viz_data_sorted_raw['lead_se'])

base_raw = alt.Chart(viz_data_sorted_raw).encode(
  y=alt.Y('state_name:N', sort=alt.EncodingSortField(field='combined', op='sum'))
)

lines_raw = base_raw.mark_rule(color='#ccc').encode(
    x='financial_satisfaction:Q',
    x2='strong_leader_pref:Q'
)

dots_fin_raw = base_raw.mark_circle(size=100, color='#1f77b4').encode(
    x='financial_satisfaction:Q',
    tooltip=[
        alt.Tooltip('state_name:N', title='State'),
        alt.Tooltip('financial_satisfaction:Q', format='.1f', title='Financial Satisfaction'),
        alt.Tooltip('fin_error_min:Q', format='.1f', title='Fin Sat CI Min'),
        alt.Tooltip('fin_error_max:Q', format='.1f', title='Fin Sat CI Max'),
        alt.Tooltip('n_size:Q', title='Sample Size')
    ]
)

dots_lead_raw = base_raw.mark_circle(size=100, color='#ff7f0e').encode(
    x='strong_leader_pref:Q',
    tooltip=[
        alt.Tooltip('state_name:N', title='State'),
        alt.Tooltip('strong_leader_pref:Q', format='.1f', title='Leader Preference'),
        alt.Tooltip('lead_error_min:Q', format='.1f', title='Lead Pref CI Min'),
        alt.Tooltip('lead_error_max:Q', format='.1f', title='Lead Pref CI Max'),
        alt.Tooltip('n_size:Q', title='Sample Size')
    ]
)

error_bars_fin_raw = base_raw.mark_errorbar(ticks=True, color='#1f77b4').encode(
    x=alt.X('fin_error_min:Q', title='Score (Scale 1-10)'),
    x2='fin_error_max:Q'
)

error_bars_lead_raw = base_raw.mark_errorbar(ticks=True, color='#ff7f0e').encode(
    x=alt.X('lead_error_min:Q'),
    x2='lead_error_max:Q'
)

final_chart_raw = (
    lines_raw +
    error_bars_fin_raw +
    error_bars_lead_raw +
    dots_fin_raw +
    dots_lead_raw
).properties(
    width=400,
    height=len(viz_data_sorted_raw) * 18,
    title="Raw Data: Financial Satisfaction vs Leader Preference"
)


viz_data = df_state_centroids.merge(capitals, left_on='state_name', right_on='state', how='inner')

viz_data.dropna(subset=['lon', 'lat'], inplace=True)

viz_data['combined'] = viz_data['financial_satisfaction'] + viz_data['strong_leader_pref']
viz_data_sorted = viz_data.sort_values('combined', ascending=False)

viz_data_sorted['fin_se'] = viz_data_sorted['fin_std'] / np.sqrt(viz_data_sorted['n_size'])
viz_data_sorted['fin_error_min'] = viz_data_sorted['financial_satisfaction'] - (z_score * viz_data_sorted['fin_se'])
viz_data_sorted['fin_error_max'] = viz_data_sorted['financial_satisfaction'] + (z_score * viz_data_sorted['fin_se'])

viz_data_sorted['lead_se'] = viz_data_sorted['lead_std'] / np.sqrt(viz_data_sorted['n_size'])
viz_data_sorted['lead_error_min'] = viz_data_sorted['strong_leader_pref'] - (z_score * viz_data_sorted['lead_se'])
viz_data_sorted['lead_error_max'] = viz_data_sorted['strong_leader_pref'] + (z_score * viz_data_sorted['lead_se'])

base_imputed = alt.Chart(viz_data_sorted).encode(
  y=alt.Y('state_name:N', sort=alt.EncodingSortField(field='combined', op='sum'))
)

lines_imputed = base_imputed.mark_rule(color='#ccc').encode(
    x='financial_satisfaction:Q',
    x2='strong_leader_pref:Q'
)

dots_fin_imputed = base_imputed.mark_circle(size=100, color='#1f77b4').encode(
    x='financial_satisfaction:Q',
    tooltip=[
        alt.Tooltip('state_name:N', title='State'),
        alt.Tooltip('financial_satisfaction:Q', format='.1f', title='Financial Satisfaction'),
        alt.Tooltip('fin_error_min:Q', format='.1f', title='Fin Sat CI Min'),
        alt.Tooltip('fin_error_max:Q', format='.1f', title='Fin Sat CI Max'),
        alt.Tooltip('n_size:Q', title='Sample Size')
    ]
)

dots_lead_imputed = base_imputed.mark_circle(size=100, color='#ff7f0e').encode(
    x='strong_leader_pref:Q',
    tooltip=[
        alt.Tooltip('state_name:N', title='State'),
        alt.Tooltip('strong_leader_pref:Q', format='.1f', title='Leader Preference'),
        alt.Tooltip('lead_error_min:Q', format='.1f', title='Lead Pref CI Min'),
        alt.Tooltip('lead_error_max:Q', format='.1f', title='Lead Pref CI Max'),
        alt.Tooltip('n_size:Q', title='Sample Size')
    ]
)

error_bars_fin_imputed = base_imputed.mark_errorbar(ticks=True, color='#1f77b4').encode(
    x=alt.X('fin_error_min:Q', title='Score (Scale 1-10)'),
    x2='fin_error_max:Q'
)

error_bars_lead_imputed = base_imputed.mark_errorbar(ticks=True, color='#ff7f0e').encode(
    x=alt.X('lead_error_min:Q'),
    x2='lead_error_max:Q'
)

final_chart_imputed = (
    lines_imputed +
    error_bars_fin_imputed +
    error_bars_lead_imputed +
    dots_fin_imputed +
    dots_lead_imputed
).properties(
    width=400,
    height=len(viz_data_sorted) * 18,
    title="KNN Imputed Data: Financial Satisfaction vs Leader Preference"
)

alt.hconcat(
    final_chart_raw,
    final_chart_imputed
).configure_view(
    stroke=None
)

line1 = alt.Chart(source).mark_line(color="blue").encode(
    x="Q287:Q",
    y="Q106:Q"
)

line2 = alt.Chart(source).mark_line(color="red").encode(
    x="Q288:Q",
    y="Q106:Q"
)

import altair as alt
import pandas as pd

alt.data_transformers.enable("vegafusion")

source_long = source.melt(
    id_vars=["Q106"],
    value_vars=["Q287", "Q288"],
    var_name="Type",
    value_name="Social_Class"
)

type_labels = {"Q287": "Perceived", "Q288": "Objective"}
source_long['Type_label'] = source_long['Type'].map(type_labels)

source_long['Social_Class'] = source_long['Social_Class'].round(0).astype(int)

final_df = source_long.groupby(['Social_Class', 'Type_label'], as_index=False)['Q106'].mean()
final_df.rename(columns={'Q106': 'mean_support'}, inplace=True)

bar_chart = alt.Chart(final_df).mark_bar(size=20).encode(
    y=alt.Y('Social_Class:O', title='Social Class (1-10)', sort='descending'),
    x=alt.X('mean_support:Q', title='Mean Support for Redistribution'),
    color=alt.Color('Type_label:N', scale=alt.Scale(range=['#4C78A8', '#E15759']), title='Class Type'),
    column=alt.Column('Type_label:N', title=None, header=alt.Header(labelFontSize=14))
).properties(
    width=250,
    height=300,
    title='Relative Deprivation: Perceived vs Objective'
).resolve_scale(
    y='shared'
)

bar_chart

import altair as alt
import pandas as pd

source = df_imputed_knn.copy()

source["trust_group"] = pd.qcut(
    source["Q71"],
    q=3,
    labels=["Low trust", "High trust"],
    duplicates='drop'
)

print("Unique values and their counts for Q71:")
print(source['Q71'].value_counts(dropna=False))

print("\nTrust group distribution:")
print(source['trust_group'].value_counts(dropna=False))

if 'X003R' in df_imputed_knn.columns:
    print("Column 'X003R' exists in the DataFrame.")
else:
    print("Column 'X003R' does not exist in the DataFrame.")

import pandas as pd

age_map_dict = {
    1.0: '16-24 years',
    2.0: '25-34 years',
    3.0: '35-44 years',
    4.0: '45-54 years',
    5.0: '55-64 years',
    6.0: '65 and over'
}

age_group_order = [
    '16-24 years',
    '25-34 years',
    '35-44 years',
    '45-54 years',
    '55-64 years',
    '65 and over'
]

print("Age group mapping and order defined.")

print("Unique values and counts for X003R:")
print(source['X003R'].value_counts(dropna=False).sort_index())

print("\nDescriptive statistics for X003R:")
print(source['X003R'].describe())

print("\nNumber of NaN values in X003R:")
print(source['X003R'].isnull().sum())

source['Age_Group_Label'] = source['X003R'].map(age_map_dict)

source_filtered = source.dropna(subset=['Q110', 'Q106', 'X003R', 'trust_group', 'Age_Group_Label'])

print("Age_Group_Label created and source_filtered DataFrame prepared.")
print("Head of source_filtered:")
display(source_filtered.head())

import altair as alt

trust_colors = alt.Scale(domain=['High trust', 'Low trust'], range=['#4c78a8', '#f58518'])

background = alt.Chart(source_filtered).mark_point(
    opacity=0.05, filled=True, size=15, color='grey'
).encode(
    x=alt.X('Q110:Q', title='Belief in Hard Work'),
    y=alt.Y('Q106:Q', title='Perceived Fairness')
)

ribbon = alt.Chart(source_filtered).mark_errorband(extent='ci', opacity=0.15).encode(
    x='Q110:Q',
    y='Q106:Q',
    color=alt.Color('trust_group:N', scale=trust_colors, legend=None) # Hide individual legends
)

lines = alt.Chart(source_filtered).transform_regression(
    'Q110', 'Q106', groupby=['trust_group', 'Age_Group_Label']
).mark_line(size=3, strokeCap='round').encode(
    x='Q110:Q',
    y='Q106:Q',
    color=alt.Color('trust_group:N', scale=trust_colors, title="Social Trust Level")
)

final_plot = alt.layer(
    background,
    ribbon,
    lines
).facet(
    facet=alt.Facet('Age_Group_Label:N', sort=age_group_order, title=None),
    columns=3
).resolve_scale(
    color='shared'
).configure_header(
    labelFontSize=14,
    labelFontWeight='bold',
    labelPadding=10
).configure_view(
    stroke=None
).configure_axis(
    domain=False,
    ticks=False,
    gridColor='#eeeeee'
)

final_plot

import altair as alt
import pandas as pd
import numpy as np

alt.data_transformers.enable("vegafusion")

def generate_mock_data():
    trust_levels = ['Most people can be trusted', 'Need to be very careful', 'Missing/No Answer']
    gov_conf = ['A great deal', 'Quite a lot', 'Not very much', 'None at all', 'Missing/No Answer']
    datasets = ['Original (Raw)', 'KNN Imputed']

    data = []
    for ds in datasets:
        for trust in trust_levels:
            for conf in gov_conf:
                count = np.random.randint(10, 100)
                if ds == 'KNN Imputed' and (trust == 'Missing/No Answer' or conf == 'Missing/No Answer'):
                    count = 0
                data.append({'Trust_Level': trust, 'Gov_Confidence': conf, 'Dataset': ds, 'count': count})
    return pd.DataFrame(data)

aggregated_confidence_data = generate_mock_data()

trust_level_order = ['Most people can be trusted', 'Need to be very careful']
gov_confidence_order = ['A great deal', 'Quite a lot', 'Not very much', 'None at all']

colors = alt.Scale(
    domain=gov_confidence_order,
    range=["#006d77", "#83c5be", "#e29578", "#ae2012"]
)

def create_clean_viz(data_subset, dataset_label):
    chart = alt.Chart(data_subset).transform_joinaggregate(
        row_total='sum(count)',
        groupby=['Trust_Level']
    ).transform_calculate(
        pct_of_total = "datum.count / datum.row_total"
    ).transform_filter(
        (alt.datum.Gov_Confidence != 'Missing/No Answer') &
        (alt.datum.Trust_Level != 'Missing/No Answer')
    ).mark_bar().encode(
        y=alt.Y('Trust_Level:N',
                sort=trust_level_order,
                title="Social Outlook"),
        x=alt.X('pct_of_total:Q',
                title="Share of Total Population",
                axis=alt.Axis(format='%'),
                scale=alt.Scale(domain=[0, 1])),
        color=alt.Color('Gov_Confidence:O',
                        scale=colors,
                        sort=gov_confidence_order,
                        title="Gov Confidence"),
        tooltip=[
            alt.Tooltip('Trust_Level:N'),
            alt.Tooltip('Gov_Confidence:N'),
            alt.Tooltip('pct_of_total:Q', format='.1%', title='Share')
        ]
    ).properties(
        height=200,
        width=500,
        title=alt.TitleParams(text=f"{dataset_label} Analysis", anchor='start')
    )
    return chart


raw_chart = create_clean_viz(
    aggregated_confidence_data[aggregated_confidence_data['Dataset'] == 'Original (Raw)'],
    'Original (Raw)'
)

knn_chart = create_clean_viz(
    aggregated_confidence_data[aggregated_confidence_data['Dataset'] == 'KNN Imputed'],
    'KNN Imputed'
)

final_viz = alt.vconcat(
    raw_chart,
    knn_chart
).resolve_scale(
    color='shared'
).configure_legend(
    orient='right',
    titleFontSize=12,
    labelFontSize=10
)

final_viz.display()